"""
PTrade API 类型声明模块 (仅供 IDE 类型检查使用)。

在策略文件顶部添加以下代码即可获得完整的类型提示:

    from typing import TYPE_CHECKING
    if TYPE_CHECKING:
        from simtradelab.ptrade._typing import *

TYPE_CHECKING 在运行时恒为 False，不会执行导入，不影响策略运行。
"""
# pyright: reportUnusedVariable=false

from __future__ import annotations

import logging as _logging
import types
from typing import Any, Callable

import numpy as _np
import pandas as _pd


# ============================================================
# PTrade API 类型声明
# ============================================================

class _Position:
    security: str
    amount: int
    cost_basis: float
    avg_cost: float
    def __getattr__(self, name: str) -> Any: ...


class _Portfolio:
    cash: float
    portfolio_value: float
    positions: dict[str, _Position]
    starting_cash: float
    positions_value: float
    returns: float
    def __getattr__(self, name: str) -> Any: ...


class _Context:
    current_dt: _pd.Timestamp
    portfolio: _Portfolio
    benchmark: str
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...


class _PanelLike:
    def __getitem__(self, key: str) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...


# -- 全局对象 --
context: _Context
g: types.SimpleNamespace
log: _logging.Logger

FUNDAMENTAL_TABLES: dict[str, list[str]]

# -- 数据查询 API --
def get_research_path() -> str: ...
def get_Ashares(date: str = ...) -> list[str]: ...
def get_trade_days(start_date: str = ..., end_date: str = ..., count: int = ...) -> list[str]: ...
def get_all_trades_days(date: str = ...) -> list[str]: ...
def get_trading_day(day: int = 0) -> str | None: ...
def is_trade() -> bool: ...
def get_fundamentals(security: str | list[str], table: str, fields: list[str], date: str = ...) -> _pd.DataFrame: ...
def get_price(security: str | list[str], start_date: str = ..., end_date: str = ..., frequency: str = "1d", fields: str | list[str] = ..., fq: str = ..., count: int = ...) -> _pd.DataFrame | _PanelLike: ...
def get_history(count: int, frequency: str = "1d", field: str | list[str] = "close", security_list: str | list[str] = ..., fq: str = ..., include: bool = False, fill: str = "nan", is_dict: bool = False) -> _pd.DataFrame | dict | _PanelLike: ...
def get_snapshot(security: str | list[str]) -> dict | _pd.DataFrame: ...
def get_stock_blocks(stock: str) -> dict: ...
def get_stock_info(stocks: str | list[str], field: str | list[str] = ...) -> dict[str, dict]: ...
def get_stock_name(stocks: str | list[str]) -> str | dict[str, str]: ...
def get_stock_status(stocks: str | list[str], query_type: str = "ST", query_date: str = ...) -> dict[str, bool]: ...
def get_stock_exrights(stock_code: str, date: str = ...) -> _pd.DataFrame | None: ...
def get_index_stocks(index_code: str, date: str = ...) -> list[str]: ...
def get_industry_stocks(industry_code: str = ...) -> dict | list[str]: ...
def check_limit(security: str | list[str], query_date: str = ...) -> dict[str, int]: ...

# -- 交易 API --
def order(security: str, amount: int, limit_price: float = ...) -> str | None: ...
def order_target(security: str, amount: int, limit_price: float = ...) -> str | None: ...
def order_value(security: str, value: float, limit_price: float = ...) -> str | None: ...
def order_target_value(security: str, value: float, limit_price: float = ...) -> str | None: ...
def cancel_order(order: object) -> bool: ...
def get_open_orders() -> list: ...
def get_orders(security: str = ...) -> list: ...
def get_order(order_id: str) -> object | None: ...
def get_trades(security: str = ...) -> list: ...
def get_position(security: str) -> _Position | None: ...
def get_positions(security_list: list[str] = ...) -> dict[str, _Position]: ...

# -- 配置 API --
def set_benchmark(benchmark: str) -> None: ...
def set_universe(stocks: str | list[str]) -> None: ...
def set_commission(commission_ratio: float = 0.0003, min_commission: float = 5.0, type: str = "STOCK") -> None: ...
def set_slippage(slippage: float = 0.0) -> None: ...
def set_fixed_slippage(fixedslippage: float = 0.001) -> None: ...
def set_limit_mode(limit_mode: str = "LIMIT") -> None: ...
def set_volume_ratio(volume_ratio: float = 0.25) -> None: ...
def set_yesterday_position(poslist: list[dict]) -> None: ...
def set_parameters(params: dict) -> None: ...

# -- 调度 API --
def run_interval(context: object, func: Callable[..., object], seconds: int = 10) -> None: ...
def run_daily(context: object, func: Callable[..., object], time: str = "9:31") -> None: ...

# -- 工具 API --
def get_user_name() -> str: ...
def convert_position_from_csv(file_path: str) -> list[dict]: ...

# -- 技术指标 API --
def get_MACD(close: _np.ndarray, short: int = 12, long: int = 26, m: int = 9) -> tuple[_np.ndarray, _np.ndarray, _np.ndarray]: ...
def get_KDJ(high: _np.ndarray, low: _np.ndarray, close: _np.ndarray, n: int = 9, m1: int = 3, m2: int = 3) -> tuple[_np.ndarray, _np.ndarray, _np.ndarray]: ...
def get_RSI(close: _np.ndarray, n: int = 6) -> _np.ndarray: ...
def get_CCI(high: _np.ndarray, low: _np.ndarray, close: _np.ndarray, n: int = 14) -> _np.ndarray: ...

# -- 索引 API --
def prebuild_date_index(stocks: list[str] | None = ...) -> None: ...
def get_stock_date_index(stock: str) -> tuple[dict, list]: ...
